# the docker-compose version, not the script/container version
version: '3.7'

services:
  thredds-production:
    container_name: thredds
    image: unidata/thredds-docker:latest
    build:
      context: ""
    ports:
      - 8080:8080
    volumes:
      # THREDDS .XML Config Files
      - /Users/286329i/Projects/IVAN_Data_Warehousing/THREDDS_Demo/Config:/usr/local/tomcat/content/thredds
      # Data Location
      - /Users/286329i/Projects/IVAN_Data_Warehousing/THREDDS_Demo/Data:/usr/local/tomcat/content/thredds/public/data